---
abstract: 'The fantastic new SVG::Convert!'
author: 'Toru Yamaguchi <zigorou@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.67'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: SVG-Convert
no_index:
  directory:
    - inc
    - t
requires:
  Carp::Clan: 0
  Class::Accessor::Fast: 0
  Module::Load: 0
  Module::Pluggable::Fast: 0
  Params::Validate: 0
  Scalar::Util: 0
  XML::LibXML: 0
version: 0.02
